# Generated by Django 5.1.1 on 2024-09-07 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='media_proof',
            field=models.FileField(blank=True, null=True, upload_to='post_media/'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('regular', 'Regular Post'), ('donation', 'Donation Request')], default='regular', max_length=10),
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prosthetic_type', models.CharField(max_length=100)),
                ('measurements', models.TextField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donation_request', to='posts.post')),
            ],
        ),
    ]
