# Generated by Django 5.1.1 on 2024-09-08 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_is_approved_post_media_proof_post_post_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media_proof',
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donation_details', to='posts.post'),
        ),
    ]
