# Generated by Django 5.1.1 on 2024-09-10 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_share_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='donation_request_images/')),
                ('donation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.donationrequest')),
            ],
        ),
    ]
