# Generated by Django 5.1.1 on 2024-09-10 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='donation_request_files/')),
                ('donation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='posts.donationrequest')),
            ],
        ),
    ]
