# Generated by Django 2.2 on 2025-07-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20250705_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('regular', 'Regular Post'), ('donation', 'Donation Request')], default='regular', max_length=20),
        ),
    ]
