# Generated by Django 5.1.1 on 2024-09-05 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_verified_memberapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberapplication',
            name='admin_notes',
        ),
    ]
