# Generated by Django 5.1.1 on 2024-09-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_memberprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='profile_photos'),
        ),
    ]
