# Generated by Django 5.2.4 on 2025-07-06 15:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_alter_donationcomment_id_alter_donationgoal_id"),
        ("posts", "0013_alter_comment_id_alter_donationrequest_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="donation_type",
            field=models.CharField(
                choices=[("one_time", "One-time"), ("monthly", "Monthly")],
                default="one_time",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MonthlySubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("donor_name", models.CharField(blank=True, max_length=100)),
                ("donor_email", models.EmailField(max_length=254)),
                (
                    "monthly_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("incomplete", "Incomplete"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("next_billing_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=200),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=200)),
                ("stripe_price_id", models.CharField(blank=True, max_length=200)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "donor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_subscriptions",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="donation",
            name="monthly_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="donations.monthlysubscription",
            ),
        ),
        migrations.AddIndex(
            model_name="monthlysubscription",
            index=models.Index(fields=["status"], name="donations_m_status_542895_idx"),
        ),
        migrations.AddIndex(
            model_name="monthlysubscription",
            index=models.Index(
                fields=["donor", "status"], name="donations_m_donor_i_92bb78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlysubscription",
            index=models.Index(
                fields=["next_billing_date"], name="donations_m_next_bi_785097_idx"
            ),
        ),
    ]
